[appconfigs]
None = {}

[connectivity]
dbsync_url = "postgres://user:password@localhost:5432/testnet"
grpc_cache_size  = 50
submit_endpoint_1 = "http://localhost:8090/api/submit/tx"
submit_endpoint_2 = ""
submit_endpoint_3 = ""
protocol_parameter_path = "/protocol_parameters_preview.json"
cert_private_key = ""
cert_pub_key = ""
